# Generated by Django 3.2.13 on 2022-10-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clubs',
            field=models.ManyToManyField(related_name='users', to='clubs.Club'),
        ),
    ]
