# Generated by Django 3.2.13 on 2022-10-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
